name: 'Welcome new contributors'

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greet-the-contributor:
    runs-on: ubuntu-latest
    steps:
    - uses: garg3133/welcome-new-contributors@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! Thanks for opening your first issue at JagratiWebApp. We really appreciate it. :raised_hands:'
        pr-message: 'Congratulations for making your first Pull Request at JagratiWebApp!! :tada: Someone from our team will review it soon.'
